export const ColorConfig = [
    { cuy: 'x', color: 'rgb(48, 44, 44)' },
    { cuy: 'ada', color: 'rgb(60, 200, 200)' },
    { cuy: 'amp', color: 'rgb(45, 174, 228)' },
    { cuy: 'ant', color: 'rgb(44, 211, 225)' },
    { cuy: 'ardr', color: 'rgb(60, 135, 199)' },
    { cuy: 'ark', color: 'rgb(247, 0, 0)' },
    { cuy: 'bat', color: 'rgb(255, 80, 0)' },
    { cuy: 'bcc', color: 'rgb(247, 147, 28)' },
    { cuy: 'bch', color: 'rgb(247, 147, 26)' },
    { cuy: 'bcn', color: 'rgb(240, 64, 134)' },
    { cuy: 'bnb', color: 'rgb(243, 186, 47)' },
    { cuy: 'btc', color: 'rgb(247, 147, 26)' },
    { cuy: 'btcd', color: 'rgb(255, 102, 0)' },
    { cuy: 'bts', color: 'rgb(53, 186, 235)' },
    { cuy: 'dash', color: 'rgb(28, 117, 188)' },
    { cuy: 'dcr', color: 'rgb(46, 214, 161)' },
    { cuy: 'dgb', color: 'rgb(0, 106, 210)' },
    { cuy: 'dgd', color: 'rgb(244, 208, 41)' },
    { cuy: 'doge', color: 'rgb(195, 166, 52)' },
    { cuy: 'emc', color: 'rgb(180, 159, 252)' },
    { cuy: 'eos', color: 'rgb(180, 159, 252)' },
    { cuy: 'etc', color: 'rgb(102, 144, 115)' },
    { cuy: 'eth', color: 'rgb(98, 126, 234)' },
    { cuy: 'fct', color: 'rgb(65, 123, 164)' },
    { cuy: 'game', color: 'rgb(152, 192, 31)' },
    { cuy: 'gbyte', color: 'rgb(48, 44, 44)' },
    { cuy: 'gno', color: 'rgb(0, 166, 196)' },
    { cuy: 'gnt', color: 'rgb(0, 29, 87)' },
    { cuy: 'hsr', color: 'rgb(86, 66, 142)' },
    { cuy: 'icn', color: 'rgb(76, 111, 140)' },
    { cuy: 'kmd', color: 'rgb(50, 100, 100)' },
    { cuy: 'knc', color: 'rgb(24, 140, 146)' },
    { cuy: 'lkk', color: 'rgb(157, 1, 235)' },
    { cuy: 'lsk', color: 'rgb(2, 136, 209)' },
    { cuy: 'ltc', color: 'rgb(203, 198, 198)' },
    { cuy: 'maid', color: 'rgb(85, 146, 215)' },
    { cuy: 'miota', color: 'rgb(36, 36, 36)' },
    { cuy: 'mln', color: 'rgb(11, 21, 41)' },
    { cuy: 'mona', color: 'rgb(240, 219, 176)' },
    { cuy: 'neo', color: 'rgb(0, 0, 0)' },
    { cuy: 'nlg', color: 'rgb(42, 176, 253)' },
    { cuy: 'nmc', color: 'rgb(24, 108, 157)' },
    { cuy: 'nxt', color: 'rgb(0, 143, 187)' },
    { cuy: 'omg', color: 'rgb(26, 83, 240)' },
    { cuy: 'pay', color: 'rgb(48, 44, 44)' },
    { cuy: 'pivx', color: 'rgb(94, 71, 120)' },
    { cuy: 'pot', color: 'rgb(16, 91, 47)' },
    { cuy: 'ppc', color: 'rgb(60, 176, 84)' },
    { cuy: 'ppt', color: 'rgb(21, 39, 67)' },
    { cuy: 'qtum', color: 'rgb(46, 154, 208)' },
    { cuy: 'rep', color: 'rgb(96, 42, 82)' },
    { cuy: 'salt', color: 'rgb(27, 238, 244)' },
    { cuy: 'sc', color: 'rgb(0, 203, 160)' },
    { cuy: 'sngls', color: 'rgb(179, 13, 35)' },
    { cuy: 'steem', color: 'rgb(75, 162, 242)' },
    { cuy: 'strat', color: 'rgb(19, 135, 201)' },
    { cuy: 'trx', color: 'rgb(0, 0, 0)' },
    { cuy: 'usdt', color: 'rgb(38, 161, 123)' },
    { cuy: 'vtc', color: 'rgb(53, 99, 62)' },
    { cuy: 'waves', color: 'rgb(0, 150, 220)' },
    { cuy: 'xcp', color: 'rgb(237, 22, 80)' },
    { cuy: 'xem', color: 'rgb(103, 178, 232)' },
    { cuy: 'xlm', color: 'rgb(20, 182, 231)' },
    { cuy: 'xmr', color: 'rgb(255, 102, 0)' },
    { cuy: 'xrp', color: 'rgb(0, 170, 228)' },
    { cuy: 'xtz', color: 'rgb(166, 224, 0)' },
    { cuy: 'zec', color: 'rgb(236, 178, 68)' }
    ];

export const CoinList = [ { code: 'ADA', name: 'ADA' },
    { code: 'ANT', name: 'Aragon' },
    { code: 'ARDR', name: 'ARDR' },
    { code: 'ARK', name: 'ARK' },
    { code: 'REP', name: 'Augur' },
    { code: 'BAT', name: 'BAT' },
    { code: 'BTC', name: 'Bitcoin' },
    { code: 'BCH', name: 'Bitcoin Cash' },
    { code: 'BTCD', name: 'BitcoinDark' },
    { code: 'BTS', name: 'BitShares' },
    { code: 'GBYTE', name: 'Byteball' },
    { code: 'BCN', name: 'Bytecoin' },
    { code: 'XCP', name: 'Counterparty' },
    { code: 'DGD', name: 'DarkGoldCoin' },
    { code: 'DASH', name: 'Dash' },
    { code: 'DCR', name: 'Decred' },
    { code: 'DGB', name: 'Digibyte' },
    { code: 'DOGE', name: 'Dogecoin' },
    { code: 'EMC', name: 'Emercoin' },
    { code: 'EOS', name: 'EOS' },
    { code: 'ETH', name: 'Ethereum' },
    { code: 'ETC', name: 'Ethereum Classic' },
    { code: 'FCT', name: 'Factom' },
    { code: 'GAME', name: 'GameCredits' },
    { code: 'GNO', name: 'GNO' },
    { code: 'GNT', name: 'Golem' },
    { code: 'NLG', name: 'Gulden' },
    { code: 'HSR', name: 'HSR' },
    { code: 'ICN', name: 'Iconomi' },
    { code: 'KNC', name: 'KhanCoin' },
    { code: 'KMD', name: 'KMD' },
    { code: 'LSK', name: 'Lisk' },
    { code: 'LTC', name: 'Litecoin' },
    { code: 'MAID', name: 'MaidSafeCoin' },
    { code: 'MLN', name: 'MLN' },
    { code: 'MONA', name: 'MonaCoin' },
    { code: 'XMR', name: 'Monero' },
    { code: 'NMC', name: 'Namecoin' },
    { code: 'XEM', name: 'NEM' },
    { code: 'NEO', name: 'NEO' },
    { code: 'NXT', name: 'NXT' },
    { code: 'OMG', name: 'OMG' },
    { code: 'PAY', name: 'PAY' },
    { code: 'PPC', name: 'Peercoin' },
    { code: 'PIVX', name: 'PIVX' },
    { code: 'POT', name: 'Potcoin' },
    { code: 'PPT', name: 'PPT' },
    { code: 'QTUM', name: 'QTUM' },
    { code: 'XRP', name: 'Ripple' },
    { code: 'SALT', name: 'SALT' },
    { code: 'SC', name: 'Siacoin' },
    { code: 'SNGLS', name: 'SNGLS' },
    { code: 'STEEM', name: 'Steem' },
    { code: 'XLM', name: 'Stellar' },
    { code: 'STRAT', name: 'STRAT' },
    { code: 'AMP', name: 'Synereo' },
    { code: 'TRX', name: 'TRX' },
    { code: 'VTC', name: 'Vertcoin' },
    { code: 'WAVES', name: 'WAVES' },
    { code: 'XTZ', name: 'XTZ' },
    { code: 'ZEC', name: 'Zcash' } ];

export const list = ["0x" , "bcn" , "doge" , "gnt" , "miota" , "pivx" , "steem" , "xmr" , "ada" , "bnb" , "emc" , "hsr" , "mln" , "pot" , "strat" , "xrp" , "amp" , "btc" , "eos" , "icn" , "mona" , "ppc" , "trx" , "xtz" , "ant" , "btcd" , "etc" , "kmd" , "neo" , "ppt" , "usdt" , "zec" , "ardr" , "bts" , "eth" , "knc" , "nlg" , "qtum" , "vtc" , "ark" , "dash" , "fct" , "lkk" , "nmc" , "rep" , "waves" , "bat" , "dcr" , "game" , "lsk" , "nxt" , "salt" , "xcp" , "bcc" , "dgb" , "gbyte" , "ltc" , "omg" , "sc" , "xem" , "bch" , "dgd" , "gno" , "maid" , "pay" , "sngls" , "xlm", "more"];
